stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

before_script:
#  - echo "Before script section"
#  - java -version
#  - mvn –version
#  - docker --version
  - apt-get update && apt-get -y install openjdk-17-jdk #  && apt-get -y install maven && apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Compiling the code..."
#    - java -version
#    - mvn –version
#    - docker --version
    - mvn package -Dmaven.test.skip
    - echo "Compile complete."
    - uname -a
  artifacts:
    paths:
      - target/*.jar
test-job:       # This job runs in the build stage, which runs first.
  stage: test
  script:
    - echo "Start tests"
    - mvn test
    - echo "End tests"

deploy-job:       # This job runs in the build stage, which runs first.
  stage: deploy
  script:
    - docker build -t troegor/wiki-info:0.1 .
    - docker login -u "$DOCKERHUB_LOGIN" -p "$DOCKERHUB_PASSWORD" docker.io
    - docker push index.docker.io/troegor/wiki-info:0.1
